#!/usr/bin/env node

/**
 * Debug script to prepare dev environment with cleared check history
 * Run with: npm run dev:clear
 * 
 * This will inject a script into index.html that clears localStorage on load,
 * then starts the dev server.
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

console.log('\n🗑️  PrintChecks - Clear History Debug Mode\n');
console.log('This will clear all check history from localStorage on next page load.\n');

// Path to the public directory and index.html
const publicDir = path.join(__dirname, '../public');
const indexPath = path.join(__dirname, '../index.html');

// Create a temporary clear-storage.js file in public
const clearStorageScript = `
// Auto-generated by clear-history.js - Clears localStorage on load
(function() {
  console.log('%c🗑️ DEBUG MODE: Clearing check history...', 'color: red; font-weight: bold; font-size: 14px;');
  localStorage.removeItem('checkList');
  console.log('%c✅ Check history cleared!', 'color: green; font-weight: bold; font-size: 14px;');
  console.log('%c⚠️ Remove scripts/clear-history.js injection to disable this.', 'color: orange; font-size: 12px;');
})();
`;

// Ensure public directory exists
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

// Write the clear storage script
const clearScriptPath = path.join(publicDir, 'clear-storage.js');
fs.writeFileSync(clearScriptPath, clearStorageScript, 'utf8');

console.log('✅ Created temporary clear-storage.js in public/');

// Read index.html and inject the script reference
let indexContent = fs.readFileSync(indexPath, 'utf8');

// Check if script is already injected
if (!indexContent.includes('clear-storage.js')) {
  // Inject before closing </head>
  indexContent = indexContent.replace(
    '</head>',
    '  <script src="/clear-storage.js"></script>\n  </head>'
  );
  fs.writeFileSync(indexPath, indexContent, 'utf8');
  console.log('✅ Injected clear script into index.html');
}

console.log('\n📝 localStorage will be cleared when you open the app');
console.log('🚀 Starting dev server...\n');
console.log('⚠️  Remember to run "npm run dev" (without :clear) after debugging!\n');

// Start the vite dev server
const vite = spawn('npm', ['run', 'dev'], { 
  stdio: 'inherit',
  shell: true 
});

// Cleanup on exit
process.on('SIGINT', () => {
  console.log('\n\n🧹 Cleaning up...');
  
  // Remove the clear script from index.html
  let indexContent = fs.readFileSync(indexPath, 'utf8');
  indexContent = indexContent.replace(
    /\s*<script src="\/clear-storage\.js"><\/script>\n?/g,
    ''
  );
  fs.writeFileSync(indexPath, indexContent, 'utf8');
  
  // Remove the clear-storage.js file
  if (fs.existsSync(clearScriptPath)) {
    fs.unlinkSync(clearScriptPath);
  }
  
  console.log('✅ Cleanup complete');
  process.exit(0);
});

